export enum Components {
  ITAlert = 'it-alert',
  ITAvatar = 'it-avatar',
  ITAvatarGroup = 'it-avatar-group',
  ITIcon = 'it-icon',
  ITTag = 'it-tag',
  ITCheckbox = 'it-checkbox',
  ITDivider = 'it-divider',
  ITDrawer = 'it-drawer',
  ITBadge = 'it-badge',
  ITButton = 'it-button',
  ITButtonGroup = 'it-button-group',
  ITSpinner = 'it-spinner',
  ITSlider = 'it-slider',
  ITSwitch = 'it-switch',
  ITCollapse = 'it-collapse',
  ITCollapseItem = 'it-collapse-item',
  ITTextarea = 'it-textarea',
  ITTooltip = 'it-tooltip',
  ITToggle = 'it-toggle',
  ITRadio = 'it-radio',
  ITProgressbar = 'it-progressbar',
  ITInput = 'it-input',
  ITNumberInput = 'it-number-input',
}
