export enum Components {
  ITAlert = 'it-alert',
  ITAvatar = 'it-avatar',
  ITIcon = 'it-icon',
  ITTag = 'it-tag',
  ITCheckbox = 'it-checkbox',
  ITDivider = 'it-divider',
  ITBadge = 'it-badge',
  ITButton = 'it-button',
  ITButtonGroup = 'it-button-group',
  ITSpinner = 'it-spinner',
  ITCollapse = 'it-collapse',
  ITCollapseItem = 'it-collapse-item',
  ITTextarea = 'it-textarea',
  ITTooltip = 'it-tooltip',
}
