name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./docs

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
