name: cd

on: [push, pull_request]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    # defaults:
    #   run:
    #     working-directory: ./docs

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: yarn

      - name: Install dependencies of docs
        working-directory: ./docs
        run: yarn

      - name: Generate
        working-directory: ./docs
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
